apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.build.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pgdb
  name: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.build.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pgdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        image: postgres
        imagePullPolicy: ""
        name: pgdb
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdb-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: pgdb-data
        persistentVolumeClaim:
          claimName: pgdb-data
status: {}
