apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.build.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: pgdb
  name: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.build.yml
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: pgdb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: databerry
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: postgres
          imagePullPolicy: Always
          name: pgdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdb-data
      restartPolicy: Always
      volumes:
        - name: pgdb-data
          persistentVolumeClaim:
            claimName: pgdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: pgdb
spec:
  type: ClusterIP
  selector:
    io.kompose.service: pgdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
